/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.GuardiaGUI;

import Administracion.Guardia;
import check_in.Visitante;

/**
 *
 * @author LENOVO
 */
public class CheckInGUI extends javax.swing.JPanel {
    private final Guardia guardia;
    /**
     * Creates new form CheckIn
     */
    public CheckInGUI(Guardia guardia) {
        initComponents();
        this.guardia = guardia;
        btSolicitarAprobacion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerCI = new javax.swing.JTabbedPane();
        pnVisitor = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreVisita = new javax.swing.JTextField();
        txtPersonaAVisitar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMotivoVisita = new javax.swing.JTextArea();
        lblVehiculo = new javax.swing.JLabel();
        necesitaEstacionamiento = new javax.swing.JRadioButton();
        btSolicitarAprobacion = new javax.swing.JButton();
        lblDate = new javax.swing.JLabel();
        lblHour = new javax.swing.JLabel();
        fechaIngresoVisita = new javax.swing.JTextField();
        horaIngresoVisita = new javax.swing.JTextField();
        btRealizarRegistro = new javax.swing.JButton();
        pnService = new javax.swing.JPanel();
        lblName2 = new javax.swing.JLabel();
        txPersonaServicio = new javax.swing.JTextField();
        lblVehiculo2 = new javax.swing.JLabel();
        checkServicioAuto = new javax.swing.JRadioButton();
        lblDate2 = new javax.swing.JLabel();
        lblHour2 = new javax.swing.JLabel();
        txtFIngresoServicio = new javax.swing.JTextField();
        txtHIngresoServicio = new javax.swing.JTextField();
        btRealizarRegistroServicio = new javax.swing.JButton();
        pnProfile = new javax.swing.JPanel();
        lblDate1 = new javax.swing.JLabel();
        lblHour1 = new javax.swing.JLabel();
        txtFechaIn = new javax.swing.JTextField();
        txtHoraIn = new javax.swing.JTextField();
        btRealizarRegistroPropio = new javax.swing.JButton();

        containerCI.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "REGISTRAR INGRESO", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 18), new java.awt.Color(51, 51, 51))); // NOI18N

        lblName.setText("Nombre:");

        jLabel2.setText("Persona a visitar:");

        jLabel3.setText("Motivo de visita:");

        txtMotivoVisita.setColumns(20);
        txtMotivoVisita.setRows(5);
        jScrollPane1.setViewportView(txtMotivoVisita);

        lblVehiculo.setText("¿Tiene vehículo?");

        necesitaEstacionamiento.setText("Si");

        btSolicitarAprobacion.setText("Solicitar autorización");
        btSolicitarAprobacion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblDate.setText("Fecha ingreso:");

        lblHour.setText("Hora ingreso:");

        btRealizarRegistro.setText("Realizar registro");
        btRealizarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRealizarRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnVisitorLayout = new javax.swing.GroupLayout(pnVisitor);
        pnVisitor.setLayout(pnVisitorLayout);
        pnVisitorLayout.setHorizontalGroup(
            pnVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnVisitorLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(pnVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(lblName)
                        .addGroup(pnVisitorLayout.createSequentialGroup()
                            .addComponent(lblVehiculo)
                            .addGap(25, 25, 25)))
                    .addComponent(lblDate)
                    .addComponent(fechaIngresoVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNombreVisita, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addComponent(txtPersonaAVisitar)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(lblHour, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(pnVisitorLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(horaIngresoVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnVisitorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(necesitaEstacionamiento)
                    .addComponent(btSolicitarAprobacion))
                .addGap(132, 132, 132))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnVisitorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btRealizarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnVisitorLayout.setVerticalGroup(
            pnVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnVisitorLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtNombreVisita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPersonaAVisitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(btSolicitarAprobacion)
                .addGap(18, 18, 18)
                .addGroup(pnVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehiculo)
                    .addComponent(necesitaEstacionamiento))
                .addGap(27, 27, 27)
                .addGroup(pnVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(lblHour, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaIngresoVisita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaIngresoVisita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRealizarRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        containerCI.addTab("Visitante", pnVisitor);

        lblName2.setText("Nombre:");

        lblVehiculo2.setText("¿Tiene vehículo?");

        checkServicioAuto.setText("Si");

        lblDate2.setText("Fecha ingreso:");

        lblHour2.setText("Hora ingreso:");

        btRealizarRegistroServicio.setText("Realizar registro");
        btRealizarRegistroServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRealizarRegistroServicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnServiceLayout = new javax.swing.GroupLayout(pnService);
        pnService.setLayout(pnServiceLayout);
        pnServiceLayout.setHorizontalGroup(
            pnServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnServiceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btRealizarRegistroServicio)
                .addGap(132, 132, 132))
            .addGroup(pnServiceLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(pnServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnServiceLayout.createSequentialGroup()
                        .addGroup(pnServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblVehiculo2)
                            .addComponent(lblName2)
                            .addComponent(lblDate2))
                        .addGap(18, 18, 18)
                        .addGroup(pnServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txPersonaServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnServiceLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(checkServicioAuto)))
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(pnServiceLayout.createSequentialGroup()
                        .addGroup(pnServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFIngresoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblHour2)
                                .addComponent(txtHIngresoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnServiceLayout.setVerticalGroup(
            pnServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnServiceLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName2)
                    .addComponent(txPersonaServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(pnServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehiculo2)
                    .addComponent(checkServicioAuto))
                .addGap(35, 35, 35)
                .addComponent(lblDate2)
                .addGap(18, 18, 18)
                .addComponent(txtFIngresoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHour2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtHIngresoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btRealizarRegistroServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        containerCI.addTab("Servicio", pnService);

        lblDate1.setText("Fecha ingreso:");

        lblHour1.setText("Hora ingreso:");

        btRealizarRegistroPropio.setText("Realizar registro");
        btRealizarRegistroPropio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRealizarRegistroPropioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnProfileLayout = new javax.swing.GroupLayout(pnProfile);
        pnProfile.setLayout(pnProfileLayout);
        pnProfileLayout.setHorizontalGroup(
            pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfileLayout.createSequentialGroup()
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnProfileLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnProfileLayout.createSequentialGroup()
                                .addComponent(lblHour1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtHoraIn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnProfileLayout.createSequentialGroup()
                                .addComponent(lblDate1)
                                .addGap(31, 31, 31)
                                .addComponent(txtFechaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnProfileLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btRealizarRegistroPropio)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        pnProfileLayout.setVerticalGroup(
            pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfileLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate1)
                    .addComponent(txtFechaIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHour1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(btRealizarRegistroPropio)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        containerCI.addTab("Perfil", pnProfile);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(containerCI, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(containerCI, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btRealizarRegistroPropioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRealizarRegistroPropioActionPerformed
        guardia.realizarCheckIn(txtFechaIn.getText(), txtHoraIn.getText());
    }//GEN-LAST:event_btRealizarRegistroPropioActionPerformed

    private void btRealizarRegistroServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRealizarRegistroServicioActionPerformed
        guardia.registrarEntrada(txPersonaServicio.getText(), txtFIngresoServicio.getText(), txtHIngresoServicio.getText(), checkServicioAuto.isContentAreaFilled());
    }//GEN-LAST:event_btRealizarRegistroServicioActionPerformed

    private void btRealizarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRealizarRegistroActionPerformed
        Visitante visitante = new Visitante(txtMotivoVisita.getText(),txtNombreVisita.getText(),txtPersonaAVisitar.getText());
        guardia.registrarEntrada(visitante, fechaIngresoVisita.getText(), horaIngresoVisita.getText(), necesitaEstacionamiento.isContentAreaFilled());
    }//GEN-LAST:event_btRealizarRegistroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRealizarRegistro;
    private javax.swing.JButton btRealizarRegistroPropio;
    private javax.swing.JButton btRealizarRegistroServicio;
    private javax.swing.JButton btSolicitarAprobacion;
    private javax.swing.JRadioButton checkServicioAuto;
    private javax.swing.JTabbedPane containerCI;
    private javax.swing.JTextField fechaIngresoVisita;
    private javax.swing.JTextField horaIngresoVisita;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDate1;
    private javax.swing.JLabel lblDate2;
    private javax.swing.JLabel lblHour;
    private javax.swing.JLabel lblHour1;
    private javax.swing.JLabel lblHour2;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblVehiculo;
    private javax.swing.JLabel lblVehiculo2;
    private javax.swing.JRadioButton necesitaEstacionamiento;
    private javax.swing.JPanel pnProfile;
    private javax.swing.JPanel pnService;
    private javax.swing.JPanel pnVisitor;
    private javax.swing.JTextField txPersonaServicio;
    private javax.swing.JTextField txtFIngresoServicio;
    private javax.swing.JTextField txtFechaIn;
    private javax.swing.JTextField txtHIngresoServicio;
    private javax.swing.JTextField txtHoraIn;
    private javax.swing.JTextArea txtMotivoVisita;
    private javax.swing.JTextField txtNombreVisita;
    private javax.swing.JTextField txtPersonaAVisitar;
    // End of variables declaration//GEN-END:variables
}
