/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.GuardiaGUI;

import Administracion.Administrador;
import Administracion.Guardia;
import Administracion.Residente;
import BD.BaseDeDatos;
import GUI.AdminGUI.AdminMenu;
import GUI.MensajeGUI.GUIBandejaDeEntrada;
import GUI.MensajeGUI.GUIMensaje;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author MARQUEZ
 */
public class GuardiaMenu extends javax.swing.JFrame {
    private final Administrador admin;
    /**
     * Creates new form GuardiaMenu
     */
    public GuardiaMenu(Administrador admin) {
        initComponents();
        this.admin = admin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btRegistrarEntradaV = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btSalir = new javax.swing.JButton();
        btRegistrarEntradaP = new javax.swing.JButton();
        btRegistrarEntradaS = new javax.swing.JButton();
        btVerHistorialVisitas = new javax.swing.JButton();
        btVerHistorialPropio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btRegistrarEntradaV.setText("Registrar entrada visita");
        btRegistrarEntradaV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarEntradaVActionPerformed(evt);
            }
        });

        jLabel1.setText("Bienvenido");

        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        btRegistrarEntradaP.setText("Registrar entrada propia");
        btRegistrarEntradaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarEntradaPActionPerformed(evt);
            }
        });

        btRegistrarEntradaS.setText("Registrar entrada servicio");
        btRegistrarEntradaS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarEntradaSActionPerformed(evt);
            }
        });

        btVerHistorialVisitas.setText("Ver historial visitas");
        btVerHistorialVisitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerHistorialVisitasActionPerformed(evt);
            }
        });

        btVerHistorialPropio.setText("Ver historial propio");
        btVerHistorialPropio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerHistorialPropioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btRegistrarEntradaS)
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btRegistrarEntradaV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btRegistrarEntradaP, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btVerHistorialVisitas, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btSalir)))
                .addGap(59, 160, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(btVerHistorialPropio, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(213, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btRegistrarEntradaP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRegistrarEntradaV, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRegistrarEntradaS, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btVerHistorialVisitas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSalir)
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(220, Short.MAX_VALUE)
                    .addComponent(btVerHistorialPropio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(44, 44, 44)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegistrarEntradaVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarEntradaVActionPerformed
        RegistrarVisita registroVisita = new RegistrarVisita(admin);
        registroVisita.setVisible(true);
    }//GEN-LAST:event_btRegistrarEntradaVActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        BaseDeDatos.escribirAdmin(admin);
        System.exit(0);
    }//GEN-LAST:event_btSalirActionPerformed

    private void btRegistrarEntradaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarEntradaPActionPerformed
        RegistroPropio registroPropio = new RegistroPropio(admin.getCondominio().getGuardia());
        registroPropio.setVisible(true);
    }//GEN-LAST:event_btRegistrarEntradaPActionPerformed

    private void btRegistrarEntradaSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarEntradaSActionPerformed
        RegistrarServicio registroServicio = new RegistrarServicio(admin);
        registroServicio.setVisible(true);
    }//GEN-LAST:event_btRegistrarEntradaSActionPerformed

    private void btVerHistorialVisitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerHistorialVisitasActionPerformed
        VisualizarRegistros verRegistros = new VisualizarRegistros(admin.getCondominio().getGuardia().getEntradasVisitantes());
        verRegistros.setVisible(true);
    }//GEN-LAST:event_btVerHistorialVisitasActionPerformed

    private void btVerHistorialPropioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerHistorialPropioActionPerformed
        VisualizarRegistros verRegistros = new VisualizarRegistros(admin.getCondominio().getGuardia().getHistorialDeEntradas());
        verRegistros.setVisible(true);
    }//GEN-LAST:event_btVerHistorialPropioActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegistrarEntradaP;
    private javax.swing.JButton btRegistrarEntradaS;
    private javax.swing.JButton btRegistrarEntradaV;
    private javax.swing.JButton btSalir;
    private javax.swing.JButton btVerHistorialPropio;
    private javax.swing.JButton btVerHistorialVisitas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
