/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.GuardiaGUI;

import Administracion.Guardia;
import Administracion.Residente;
import BD.BaseDeDatos;
import GUI.AdminGUI.AdminMenu;
import GUI.MensajeGUI.GUIBandejaDeEntrada;
import GUI.MensajeGUI.GUIMensaje;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author MARQUEZ
 */
public class GuardiaMenu extends javax.swing.JFrame {
    private final Guardia guardia;
    /**
     * Creates new form GuardiaMenu
     */
    public GuardiaMenu(Guardia guardia) {
        initComponents();
        this.guardia = guardia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btBandejaEntrada = new javax.swing.JButton();
        btRedactarMensaje = new javax.swing.JButton();
        btRegistrarEntradaV = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btSalir = new javax.swing.JButton();
        btRegistrarEntradaP = new javax.swing.JButton();
        btRegistrarEntradaS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btBandejaEntrada.setText("Bandeja de entrada");
        btBandejaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBandejaEntradaActionPerformed(evt);
            }
        });

        btRedactarMensaje.setText("Redactar Mensaje");
        btRedactarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRedactarMensajeActionPerformed(evt);
            }
        });

        btRegistrarEntradaV.setText("Registrar entrada visita");
        btRegistrarEntradaV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarEntradaVActionPerformed(evt);
            }
        });

        jLabel1.setText("Bienvenido");

        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        btRegistrarEntradaP.setText("Registrar entrada propia");
        btRegistrarEntradaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarEntradaPActionPerformed(evt);
            }
        });

        btRegistrarEntradaS.setText("Registrar entrada servicio");
        btRegistrarEntradaS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarEntradaSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btRegistrarEntradaV)
                    .addComponent(btRegistrarEntradaS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btRedactarMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btBandejaEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btSalir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(btRegistrarEntradaP)
                    .addContainerGap(219, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btBandejaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRegistrarEntradaV, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRedactarMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRegistrarEntradaS, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSalir)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(btRegistrarEntradaP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(192, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBandejaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBandejaEntradaActionPerformed
        GUIBandejaDeEntrada bandeja = new GUIBandejaDeEntrada(guardia, 1);
        try {
            bandeja.setListaMensajes(guardia.getBandejaDeEntrada().getListaMensajes());
        } catch (IOException ex) {
            Logger.getLogger(AdminMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        bandeja.setVisible(true);
    }//GEN-LAST:event_btBandejaEntradaActionPerformed

    private void btRedactarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRedactarMensajeActionPerformed
        /*
        GUIMensaje gUIMensaje = new GUIMensaje(guardia,1);
        // Hacer visible la nueva ventana
        gUIMensaje.setVisible(true);
        // Hacer invisible la ventana actual
        this.setVisible(false);
        // Configurar el comportamiento al cerrar la ventana de ListaResidente
        gUIMensaje.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        gUIMensaje.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
   
                // Hacer visible la ventana actual al cerrar la ventana de ListaResidente
                setVisible(true);
            }
        });
        */
    }//GEN-LAST:event_btRedactarMensajeActionPerformed

    private void btRegistrarEntradaVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarEntradaVActionPerformed
        RegistrarVisita registroVisita = new RegistrarVisita(guardia);
        registroVisita.setVisible(true);
        System.out.println(guardia.getEntradasVisitantes().toString());
    }//GEN-LAST:event_btRegistrarEntradaVActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        BaseDeDatos.escribirGuardia(guardia);
        System.exit(0);
    }//GEN-LAST:event_btSalirActionPerformed

    private void btRegistrarEntradaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarEntradaPActionPerformed
        RegistroPropio registroPropio = new RegistroPropio(guardia);
        registroPropio.setVisible(true);
        System.out.println(guardia.getEntradasVisitantes().toString());
    }//GEN-LAST:event_btRegistrarEntradaPActionPerformed

    private void btRegistrarEntradaSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarEntradaSActionPerformed
        RegistrarServicio registroServicio = new RegistrarServicio(guardia);
        registroServicio.setVisible(true);
        System.out.println(guardia.getEntradasVisitantes().toString());
    }//GEN-LAST:event_btRegistrarEntradaSActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBandejaEntrada;
    private javax.swing.JButton btRedactarMensaje;
    private javax.swing.JButton btRegistrarEntradaP;
    private javax.swing.JButton btRegistrarEntradaS;
    private javax.swing.JButton btRegistrarEntradaV;
    private javax.swing.JButton btSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
