/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.GuardiaGUI;

import Administracion.Guardia;
import static BD.BaseDeDatos.guardia;

/**
 *
 * @author MARQUEZ
 */
public class RegistrarServicio extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarServicio
     * @param guardia
     */
    public RegistrarServicio(Guardia guardia) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName2 = new javax.swing.JLabel();
        txPersonaServicio = new javax.swing.JTextField();
        lblVehiculo2 = new javax.swing.JLabel();
        checkServicioAuto = new javax.swing.JRadioButton();
        lblDate2 = new javax.swing.JLabel();
        txtFIngresoServicio = new javax.swing.JTextField();
        lblHour2 = new javax.swing.JLabel();
        txtHIngresoServicio = new javax.swing.JTextField();
        btRealizarRegistroServicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblName2.setText("Nombre:");

        lblVehiculo2.setText("¿Tiene vehículo?");

        checkServicioAuto.setText("Si");

        lblDate2.setText("Fecha ingreso:");

        lblHour2.setText("Hora ingreso:");

        btRealizarRegistroServicio.setText("Realizar registro");
        btRealizarRegistroServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRealizarRegistroServicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btRealizarRegistroServicio)
                        .addGap(86, 86, 86))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblVehiculo2)
                            .addComponent(lblName2)
                            .addComponent(lblDate2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txPersonaServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(checkServicioAuto))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFIngresoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblHour2)
                                .addComponent(txtHIngresoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(169, 169, 169)))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName2)
                    .addComponent(txPersonaServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehiculo2)
                    .addComponent(checkServicioAuto))
                .addGap(35, 35, 35)
                .addComponent(lblDate2)
                .addGap(18, 18, 18)
                .addComponent(txtFIngresoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHour2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtHIngresoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btRealizarRegistroServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRealizarRegistroServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRealizarRegistroServicioActionPerformed
        guardia.registrarEntrada(txPersonaServicio.getText(), txtFIngresoServicio.getText(), txtHIngresoServicio.getText(), checkServicioAuto.isContentAreaFilled());
    }//GEN-LAST:event_btRealizarRegistroServicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRealizarRegistroServicio;
    private javax.swing.JRadioButton checkServicioAuto;
    private javax.swing.JLabel lblDate2;
    private javax.swing.JLabel lblHour2;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblVehiculo2;
    private javax.swing.JTextField txPersonaServicio;
    private javax.swing.JTextField txtFIngresoServicio;
    private javax.swing.JTextField txtHIngresoServicio;
    // End of variables declaration//GEN-END:variables
}
